# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#080808"

# Main text color
theme[main_fg]="#ffb000"

# Title text color
theme[title]="#ffb000"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#ffffff"

# Background color of selected item in lists
theme[selected_bg]="#ffb000"

# Foreground color of selected item in lists
theme[selected_fg]="#080808"

# Color of inactive/disabled text
theme[inactive_fg]="#3a3a3a"

# Color of text appearing on top of graphs, i.e uptime and current process
theme[graph_text]="#ffd166"

# Background color of the meter
theme[meter_bg]="#181818"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#8c9b32"

# Cpu box outline color
theme[cpu_box]="#ffb000"

# Memory/disks box outline color
theme[mem_box]="#ffb000"

# Net box outline color
theme[net_box]="#ffb000"

# Processes box outline color
theme[proc_box]="#ffb000"

# Box divider line and small symbols
theme[div_line]="#262626"

# Temperature graph colors
theme[temp_start]="#8c9b32"
theme[temp_mid]="#ffb000"
theme[temp_end]="#ff5c00"

# CPU graph colors
theme[cpu_start]="#8c9b32"
theme[cpu_mid]="#ffb000"
theme[cpu_end]="#ff5c00"

# Mem/Disk free meter
theme[free_start]="#8c9b32"
theme[free_mid]="#ffb000"
theme[free_end]="#ff5c00"

# Mem/Disk cached meter
theme[cached_start]="#ffb000"
theme[cached_mid]="#ffd166"
theme[cached_end]="#ffffff"

# Mem/Disk available meter
theme[available_start]="#8c9b32"
theme[available_mid]="#ffb000"
theme[available_end]="#ff5c00"

# Mem/Disk used meter
theme[used_start]="#ffb000"
theme[used_mid]="#ff5c00"
theme[used_end]="#ff0000"

# Download graph colors
theme[download_start]="#8c9b32"
theme[download_mid]="#ffb000"
theme[download_end]="#ffd166"

# Upload graph colors
theme[upload_start]="#ffb000"
theme[upload_mid]="#ff5c00"
theme[upload_end]="#ff0000"
