theme[main_bg]="#fffdf0"
theme[main_fg]="#000000"
theme[title]="#ff006e"
theme[hi_fg]="#ff006e"
theme[selected_bg]="#ff006e"
theme[selected_fg]="#ffffff"
theme[inactive_fg]="#888888"
theme[graph_text]="#000000"
theme[meter_bg]="#e5e5e5"
theme[proc_misc]="#8338ec"

theme[cpu_box]="#000000"
theme[mem_box]="#000000"
theme[net_box]="#000000"
theme[proc_box]="#000000"
theme[div_line]="#000000"

theme[temp_start]="#00f5d4"
theme[temp_mid]="#ffbe0b"
theme[temp_end]="#ff006e"

theme[cpu_start]="#00f5d4"
theme[cpu_mid]="#ffbe0b"
theme[cpu_end]="#ff006e"

theme[free_start]="#00f5d4"
theme[free_mid]="#ffbe0b"
theme[free_end]="#ff006e"

theme[cached_start]="#ffbe0b"
theme[cached_mid]="#ff006e"
theme[cached_end]="#8338ec"

theme[available_start]="#00f5d4"
theme[available_mid]="#ffbe0b"
theme[available_end]="#ff006e"

theme[used_start]="#ffbe0b"
theme[used_mid]="#ff006e"
theme[used_end]="#8338ec"

theme[download_start]="#00f5d4"
theme[download_mid]="#3a86ff"
theme[download_end]="#ff006e"

theme[upload_start]="#ffbe0b"
theme[upload_mid]="#ff006e"
theme[upload_end]="#8338ec"
