# Foreground/Background
foreground            #cdd6f4
background            #080808
selection_foreground  #080808
selection_background  #ffb000
font_size 14.0
background_opacity 0.85

# Cursor (Glowing Amber)
cursor                #ffb000
cursor_text_color     #080808
cursor_shape          block

# Standard Colors (Amber Infused ANSI Palette)
color0  #121212
color8  #4d4d4d
color1  #ff5c5c
color9  #ff6e6e
color2  #8c9b32
color10 #a3b83b
color3  #ffb000
color11 #ffd166
color4  #ffb000
color12 #ffd166
color5  #d4a847
color13 #e5be60
color6  #8c9b32
color14 #a3b83b
color7  #cdd6f4
color15 #ffffff

# Window Layout
window_padding_width 12
confirm_os_window_close 0
